#!/bin/sh

start() {
  printf "Starting zerotier daemon: "
  start-stop-daemon -S --exec /usr/sbin/zerotier-one -- -d
  [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
  printf "Stopping zerotier daemon: "
  start-stop-daemon -K -q --pidfile /var/lib/zerotier-one.pid
  [ $? = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
  stop
  sleep 1
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
